import 'dart:async';
// import 'dart:html';

import 'package:cigi/models/card_model.dart';
import 'package:cigi/services/services.dart';
import 'package:cigi/shared/shared.dart';
import 'package:cigi/ui/pages/login/login.dart';
import 'package:cigi/ui/pages/testing_login.dart';
import 'package:cigi/ui/widgets/widget.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';

part 'home.dart';
part 'main_page.dart';
part 'search_page.dart';
part 'profile_page.dart';
part 'content_idea.dart';
part 'product_support.dart';
part 'make_it.dart';
part 'vouchers.dart';
part 'colaboration.dart';
part 'cool_spot.dart';
part 'food.dart';
part 'extreme_sport.dart';
part 'creative_goods.dart';
part 'special_event.dart';
part 'equipment.dart';
part 'crew.dart';
part 'edit_profile.dart';
part 'read_profile.dart';
part 'edit_password.dart';
// part 'login_home.dart';
// part 'bottom_nav.dart';
part 'directory.dart';
part 'tips.dart';
part 'contact.dart';
part 'cafe.dart';
part 'level.dart';
part 'voucher_detail.dart';
